#!/bin/bash -l
#
#
# http://www.ludovicocaldara.net/dba/bash-tips-4-use-logging-levels/
#
#
colblk='\033[0;30m' # Black - Regular
colred='\033[0;31m' # Red
colgrn='\033[0;32m' # Green
colylw='\033[0;33m' # Yellow
colpur='\033[0;35m' # Purple
colrst='\033[0m'    # Text Reset

verbosity=4

### verbosity levels
silent_lvl=0
crt_lvl=1
err_lvl=2
wrn_lvl=3
ntf_lvl=4
inf_lvl=5
dbg_lvl=6

## esilent prints output even in silent mode
# terminal versions
tty -s && esilent () { verb_lvl=$silent_lvl elog "$@" ;}
tty -s && enotify () { verb_lvl=$ntf_lvl elog "$@" ;}
tty -s && eok ()    { verb_lvl=$ntf_lvl elog "SUCCESS - $@" ;}
tty -s && ewarn ()  { verb_lvl=$wrn_lvl elog "${colylw}WARNING${colrst} - $@" ;}
tty -s && einfo ()  { verb_lvl=$inf_lvl elog "${colwht}INFO${colrst} ---- $@" ;}
tty -s && edebug () { verb_lvl=$dbg_lvl elog "${colgrn}DEBUG${colrst} --- $@" ;}
tty -s && eerror () { verb_lvl=$err_lvl elog "${colred}ERROR${colrst} --- $@" ;}
tty -s && ecrit ()  { verb_lvl=$crt_lvl elog "${colpur}FATAL${colrst} --- $@" ;}
tty -s && edumpvar () { for var in $@ ; do edebug "$var=${!var}" ; done }
# syslog versions
tty -s || esilent () { logger -t verb_lvl=$silent_lvl elog "$@" ;}
tty -s || enotify () { logger -t verb_lvl=$ntf_lvl elog "$@" ;}
tty -s || eok ()    { logger -t verb_lvl=$ntf_lvl elog "SUCCESS - $@" ;}
tty -s || ewarn ()  { logger -t verb_lvl=$wrn_lvl elog "${colylw}WARNING${colrst} - $@" ;}
tty -s || einfo ()  { logger -t verb_lvl=$inf_lvl elog "${colwht}INFO${colrst} ---- $@" ;}
tty -s || edebug () { logger -t verb_lvl=$dbg_lvl elog "${colgrn}DEBUG${colrst} --- $@" ;}
tty -s || eerror () { logger -t verb_lvl=$err_lvl elog "${colred}ERROR${colrst} --- $@" ;}
tty -s || ecrit ()  { logger -t verb_lvl=$crt_lvl elog "${colpur}FATAL${colrst} --- $@" ;}
tty -s || edumpvar () { for var in $@ ; do edebug "$var=${!var}" ; done }
# Error log function for terminal
elog() {
        if [ $verbosity -ge $verb_lvl ]; then
                datestring=`date +"%Y-%m-%d %H:%M:%S"`
                echo -e "$datestring - $@"
        fi
}
# Error log function for syslog
slog() {
        if [ $verbosity -ge $verb_lvl ]; then
                logger -t "$@"
        fi
}




OPTIND=1
while getopts ":sVG" opt ; do
        case $opt in
        s)
                verbosity=$silent_lvl
                edebug "-s specified: Silent mode"
                ;;
        V)
                verbosity=$inf_lvl
                edebug "-V specified: Verbose mode"
                ;;
        G)
                verbosity=$dbg_lvl
                edebug "-G specified: Debug mode"
                ;;
        esac
done

ewarn "this is a warning"
eerror "this is an error"
einfo "this is an information"
edebug "debugging"
ecrit "CRITICAL MESSAGE!"
edumpvar ORACLE_SID
